### ISSUE TITLE
Categories loader does not consume latest categories file

### ISSUE THREAD

**Issue by spikeheap** [DFE-Digital/npd-find-and-explore#131]
After loading [NPD Tables SC IN PROGRESS (AutoRecovered).xlsx](https://github.com/DFE-Digital/npd-find-and-explore/files/3127866/NPD.Tables.SC.IN.PROGRESS.AutoRecovered.xlsx) with this:

```
DfEDataTables::DataElementsLoader.new('/Users/rb/Library/Containers/com.apple.mail/Data/Library/Mail Downloads/EA8967F1-A773-49AB-AACC-4C01897BD6B9/NPD Tables SC IN PROGRESS (AutoRecovered).xlsx');nil
```

Attempting to load [Information Architecture 04-24 - MASTER.xlsx](https://github.com/DFE-Digital/npd-find-and-explore/files/3127863/Information.Architecture.04-24.-.MASTER.xlsx) with this:

```
DfEDataTables::CategoriesLoader.new('/Users/rb/Downloads/Information Architecture 04-24 - MASTER.xlsx');nil
```

Yields this:
```
Traceback (most recent call last):
       11: from (irb):3
       10: from (irb):3:in `rescue in irb_binding'
        9: from (irb):3:in `new'
        8: from app/lib/dfe_data_tables/categories_loader.rb:12:in `initialize'
        7: from app/lib/dfe_data_tables/categories_loader.rb:13:in `block in initialize'
        6: from app/lib/dfe_data_tables/categories_loader.rb:13:in `each'
        5: from app/lib/dfe_data_tables/categories_loader.rb:17:in `block (2 levels) in initialize'
        4: from app/lib/dfe_data_tables/categories_parser.rb:36:in `categories'
        3: from app/lib/dfe_data_tables/categories_parser.rb:36:in `each_with_object'
        2: from app/lib/dfe_data_tables/categories_parser.rb:38:in `block in categories'
        1: from app/lib/dfe_data_tables/categories_parser.rb:38:in `<'
ArgumentError (comparison of Integer with Range failed)
```

**Comment by krios82** [comment]
The category file, tab Attainment, is missing a header.
The first column of the headers row should contain either 'L0' or 'Standard Extract' to mark the beginning of the data section, but this is missing.

**Comment by spikeheap** [comment]
This is now fixed
